name: piantpa
description: Order Processing Application with time tracking
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  excel: ^4.0.3
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  path: ^1.9.0
  intl: ^0.19.0
  uuid: ^4.2.1
  mssql_connection: ^2.0.0

flutter:
  assets:
    - assets/images/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

